site_name: 'USP Aero Suite documentation'
docs_dir: './docs'                        # Where to find the English markdown files
site_dir: './generated'                      # Where to put the English HTML files
site_url: 'https://docs.united-security-providers.ch/usp-aero'
copyright: '&copy; 2026 United Security Providers AG. All Rights Reserved.'

# Top page MUST be in a separate branch; otherwise, whenever it's generated and
# deployed, it will delete the content of the sub-pages from that branch. That
# is why we push the top-page into a custom branch, and then merge the GIT
# branches in the "release.sh" script.
remote_branch: gh-pages-top

theme:
  name: material
  custom_dir: './overrides/'                  # This is where the customization of the theme lives
  logo: assets/images/USP-Logo-zentriert-ohne-Claim-white.png                # The logo is shared by all languages
  favicon: favicon.ico              # The favicon is shared by all languages
  language: en                                    # The build's language
  static_templates:
    - 404.html   # 404 page
extra_css:
  - assets/stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/united-security-providers/
      name: United Security Providers on Linkedin
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@United-security-providersCh
      name: United Security Providers on Youtube

plugins:
  - search:
      enabled: false
  - swagger-ui-tag:
      supportedSubmitMethods: []
      validatorUrl: none
  - privacy

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
nav:
  - Welcome: 'index.md'
  - Search: 'search.md'
  - Aero Platform: 'aero-platform/'
  - Aero WAAP: 'aero-waap/'
